# Generated by Django 6.0.4 on 2026-04-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_average_rating_item_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.user'),
        ),
    ]
