# Generated by Django 6.0.4 on 2026-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='penalty_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='max_borrow_days',
            field=models.IntegerField(default=7),
        ),
    ]
