# Generated by Django 6.0.4 on 2026-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_level_user_points_alter_user_trust_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=50.0),
        ),
    ]
