# Generated by Django 6.0.4 on 2026-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_booking_due_date_booking_penalty_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=0.0),
        ),
    ]
