# Generated by Django 6.0.4 on 2026-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_quantity_alter_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
